"""created_at Column added

Revision ID: 6805e2781da1
Revises: 4d0e6406b136
Create Date: 2025-05-07 22:20:25.404127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6805e2781da1'
down_revision = '4d0e6406b136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
