"""sent_at upadated

Revision ID: 68e1d0b3a6bb
Revises: a065a4dbe290
Create Date: 2025-05-08 10:31:02.687274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68e1d0b3a6bb'
down_revision = 'a065a4dbe290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('sent_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_at', mysql.DATETIME(), nullable=False))

    # ### end Alembic commands ###
